# Generated by Django 6.0.5 on 2026-05-20 11:12

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_version', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('chunk_hash', models.CharField(max_length=64, unique=True)),
                ('chunk_text', models.TextField()),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_dimensions', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='reports.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
