# Generated by Django 5.2 on 2026-05-20 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaircraft',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AddConstraint(
            model_name='reportaircraft',
            constraint=models.UniqueConstraint(fields=('report', 'aircraft'), name='uniq_report_aircraft'),
        ),
    ]
