# Generated by Django 6.0.5 on 2026-05-20 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('external_source_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ingested', 'Ingested'), ('validation_failed', 'Validation Failed'), ('under_review', 'Under Review'), ('requires_revision', 'Requires Revision'), ('approved_queued', 'Approved Queued'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('org_source_external_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('s3_blob_key', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected')], default='pending', max_length=16)),
                ('redaction_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('redacted', 'Redacted')], default='none', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_version', models.IntegerField()),
                ('review_stage', models.CharField(choices=[('triage', 'Triage'), ('first_review', 'First Review'), ('final_review', 'Final Review')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgReportsReadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_key', models.CharField(max_length=100, unique=True)),
                ('document', models.JSONField(default=dict)),
                ('document_version', models.IntegerField(default=1)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_read_models', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportReadModel',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='read_model', serialize=False, to='reports.report')),
                ('document', models.JSONField(default=dict)),
                ('document_version', models.IntegerField(default=1)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
